version: '3'

services:
  cams-dev-container:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of .NET: 3.1-focal, 5.0-focal, 6.0-focal
        VARIANT: "6.0-bullseye-slim"
        # Optional version of Node.js
        NODE_VERSION: "lts/*"

    volumes:
      - dev-vol:/workspace


    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: host

volumes:
  dev-vol:
